### ISSUE TITLE
Cannot load Terrarium, connection error, certificate?

### ISSUE THREAD

**Issue by timmipol** [gegy1000/Terrarium#121]
While trying create a new world or got to customization I see an error
`Failed to prepare terrarium for use! Please check your internet connection and try again.`
```
[15:10:27] [Client thread/WARN]: Failed to prepare Terrarium for use
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949) ~[?:1.8.0_51]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302) ~[?:1.8.0_51]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[?:1.8.0_51]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497) ~[?:1.8.0_51]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212) ~[?:1.8.0_51]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[?:1.8.0_51]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[?:1.8.0_51]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(AccessController.java:713) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_51]
	at net.gegy1000.earth.server.shared.ClimateRasterInitializer.getRemoteStream(ClimateRasterInitializer.java:51) ~[ClimateRasterInitializer.class:?]
	at net.gegy1000.earth.server.shared.ClimateRasterInitializer.getStream(ClimateRasterInitializer.java:37) ~[ClimateRasterInitializer.class:?]
	at net.gegy1000.earth.server.shared.ClimateRasterInitializer.initialize(ClimateRasterInitializer.java:24) ~[ClimateRasterInitializer.class:?]
	at net.gegy1000.earth.server.shared.SharedDataInitializers.lambda$initialize$0(SharedDataInitializers.java:44) ~[SharedDataInitializers.class:?]
	at net.gegy1000.earth.server.shared.SharedDataInitializers$$Lambda$188/452660386.get(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_51]
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387) ~[?:1.8.0_51]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[?:1.8.0_51]
	at sun.security.validator.Validator.validate(Validator.java:260) ~[?:1.8.0_51]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_51]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:1.8.0_51]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_51]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479) ~[?:1.8.0_51]
	... 26 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145) ~[?:1.8.0_51]
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131) ~[?:1.8.0_51]
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[?:1.8.0_51]
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382) ~[?:1.8.0_51]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[?:1.8.0_51]
	at sun.security.validator.Validator.validate(Validator.java:260) ~[?:1.8.0_51]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_51]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:1.8.0_51]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[?:1.8.0_51]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479) ~[?:1.8.0_51]
	... 26 more
```
Minecraft 1.12.2, Terrarium 1.1.8

**Comment by Groby12** [comment]
this is happening to me as well

**Comment by ekat2468** [comment]
I was having this same issue, it seems like updating Java fixed it

**Comment by Gegy** [comment]
This seems to be an issue with older versions of Java 8 making requests to Microsoft Azure due to new TLS certificates (as of 27th July) which are not supported. 

I am looking into a hackfix for this issue to install these certificates with the mod, but until then, it should be possible to resolve by updating to the latest version of Java 8 and setting the Minecraft Launcher to use that version. 🙂 

Thank you for all the reports here, and apologies for the delay!

**Comment by Gegy** [comment]
I have pushed a fix and have released [1.1.9](https://www.curseforge.com/minecraft/mc-mods/terrarium/files/3931277). 🙂 Please let me know if you encounter any issues!

**Comment by Remint32** [comment]
> I have pushed a fix and have released [1.1.9](https://www.curseforge.com/minecraft/mc-mods/terrarium/files/3931277). 🙂 Please let me know if you encounter any issues!

Still experiencing the same problem on version 1.1.9 with java 8

**Comment by Gegy** [comment]
Hi! Do you encounter this issue with only Terrarium installed? 🙂 If not, what other mods do you have installed?

**Comment by Remint32** [comment]
> Hi! Do you encounter this issue with only Terrarium installed? 🙂 If not, what other mods do you have installed?

Hi, I am only experiencing this problem with Terrarium and in principle have not experienced this problem before with other modifications.
I took your advice and upgraded **java 8** to _8u341_ and then to _8u345_ - and the problem no longer occurred (thank you very much - for me the problem is solved 👍).
I assume that people with an older version of java still have this problem.

**Comment by Remint32** [comment]
> If not, what other mods do you have installed?

```
https://teamopenindustry.cc/maven/cam72cam/immersiverailroading/ImmersiveRailroading/1.12.2-forge-1.9.1-10052c4/ImmersiveRailroading-1.12.2-forge-1.9.1-10052c4.jar
https://teamopenindustry.cc/maven/cam72cam/universalmodcore/UniversalModCore/1.12.2-forge-1.1.4-dfa6432/UniversalModCore-1.12.2-forge-1.1.4-dfa6432.jar
https://www.curseforge.com/minecraft/mc-mods/track-api/download/2825260/file
https://www.curseforge.com/minecraft/mc-mods/littletiles/download/3781003/file
https://www.curseforge.com/minecraft/mc-mods/creativecore/download/3626833/file
https://www.curseforge.com/minecraft/mc-mods/kiros-basic-blocks/download/3526794/file
https://www.curseforge.com/minecraft/mc-mods/better-foliage/download/3393955/file
https://www.curseforge.com/minecraft/mc-mods/shadowfacts-forgelin/download/2785465/file
https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty/download/3558882/file
https://www.curseforge.com/minecraft/mc-mods/wawla/download/2916368/file
https://www.curseforge.com/minecraft/mc-mods/hwyla/download/2568751/file
https://www.curseforge.com/minecraft/mc-mods/jei/download/3043174/file
https://www.curseforge.com/minecraft/mc-mods/more-overlays/download/2745657/file
https://www.curseforge.com/minecraft/mc-mods/jei-integration/download/2951731/file
https://www.curseforge.com/minecraft/mc-mods/bibliocraft/download/3647708/file
https://www.curseforge.com/minecraft/mc-mods/worldedit/download/2941712/file
https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/download/3937622/file
https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map/download/3948192/file
https://www.curseforge.com/minecraft/mc-mods/sound-filters/download/3025806/file
http://optifine.net/adloadx?f=preview_OptiFine_1.12.2_HD_U_G6_pre1.jar
https://www.curseforge.com/minecraft/mc-mods/project-red-core/download/2745545/file
https://www.curseforge.com/minecraft/mc-mods/project-red-fabrication/download/2745547/file
https://www.curseforge.com/minecraft/mc-mods/project-red-integration/download/2745548/file
https://www.curseforge.com/minecraft/mc-mods/mrtjpcore/download/2735197/file
https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8/download/2779848/file
https://www.curseforge.com/minecraft/mc-mods/cb-multipart/download/2755790/file
https://www.curseforge.com/minecraft/mc-mods/external-view-reload/download/3725234/fil
```

**Comment by Gamersooreal** [comment]
How do i know if i have the latest version of Java 8 and how do i get it. I currently have java 8 351 and the problem is still there

**Comment by Gamersooreal** [comment]
nvm i fixed it by setting the java version in the launcher using C:\Program Files\Java\jre1.8.0_351\bin\javaw.exe

**Comment by GB-glitchcore** [comment]
how do you set the java version in the launcher
is there a tab to open it

**Comment by GB-glitchcore** [comment]
i still updated my java version to the latest and i still have the problem
im using 1.12.2 should i install the java that is compatible with 1.12.2
